---
title: "titanic-analysis"
author: "José Luis Tello"
date: "8/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggthemes)
```

```{r}
train <- read.csv("data/train.csv", header = TRUE)
test <- read.csv("data/test.csv", header = TRUE)
```

```{r}
str(train)
```

```{r}
str(test)
```

## Drop NA values from test set
```{r}
test <- data.frame(test[1], Survived = rep("NA", nrow(test)), test[ , 2:ncol(test)])
```

## Merge train and test for visualization and analysis

```{r}
data <- rbind(train, test)
```

## Create file from rbind product
```{r}
write.csv(data, "./data/data.cvs", row.names = FALSE )
```

```{r}
length(data$PassengerId)
```

```{r}
length(unique(data$PassengerId))
```

```{r}
data$Survived <- as.factor(data$Survived)
table(data$Survived, dnn = "Number of Survived in Data Frame")
```

```{r}
prop.table(table(as.factor(train$Survived), dnn = "Survive and death ratio in Train Data"))
```

## Time to change type of data

```{r}
data$Pclass <- as.factor(data$Pclass)
```


```{r}
table(data$Pclass, dnn = "Pclass values in Data")
```










